import { AppConfig } from "@/lib/appConfig";
import type { UiState } from "instantsearch.js";

type PlainObject = Record<string, any>;

const MODEL_TO_MAKE = new Map<string, string>();

export function setModelMakeMap(entries: Iterable<[string, string]>) {
  for (const [model, make] of entries) {
    MODEL_TO_MAKE.set(model, make);
  }
}

export function getModelMakeMap() {
  return MODEL_TO_MAKE;
}
 
export const FILTER_KEYS: Record<string, string> = {
  location: "locations",
  vehicle_type: "vehicleTypes",
  year: "year",
  make: "makes",
  model: "models",
  exterior_color: "colors",
  body_type: "bodyStyles",
  transmission: "transmissions",
  fuel_type: "fuelTypes",
};
 
export const modelMakeAssociations = new Map<string, string>();

let activeRouterResync: (() => void) | null = null;

export function resyncInventoryUrl() {
  activeRouterResync?.();
}

export const RANGE_KEYS: Record<string, readonly [string, string]> = {
  selling_price: ["priceLow", "priceHigh"],
  odometer: ["odometerLow", "odometerHigh"],
};

 
const PUBLIC_SORT_FIELDS: Record<string, string> = {
  selling_price: "price",
};

function getPublicSort(sortBy: unknown) {
  if (typeof sortBy !== "string") return null;

  const sortExpression = sortBy.split("/sort/")[1];
  if (!sortExpression) return null;
 
  const criteria = sortExpression.split(",");
  const primaryCriterion = criteria.find((c) => !c.startsWith("status_rank:")) || criteria[0];
  const [field, direction] = primaryCriterion.split(":", 2);
  if (!field || !direction) return null;

  return {
    field: PUBLIC_SORT_FIELDS[field] || field,
    direction: direction.toUpperCase(),
  };
}

function getInternalSortField(field: string) {
  return Object.entries(PUBLIC_SORT_FIELDS).find(([, publicField]) => publicField === field)?.[0] || field;
}

let isInternalUrlWrite = false;
let historyPatched = false;
const externalUrlListeners = new Set<() => void>();

function watchExternalUrlChanges() {
  if (historyPatched || typeof window === "undefined") return;
  historyPatched = true;

  const originalPushState = window.history.pushState.bind(window.history);
  const originalReplaceState = window.history.replaceState.bind(window.history);
  const notify = () => externalUrlListeners.forEach((listener) => listener());

  window.history.pushState = function (...args: Parameters<typeof originalPushState>) {
    const result = originalPushState(...args);
    if (!isInternalUrlWrite) notify();
    return result;
  };
  window.history.replaceState = function (...args: Parameters<typeof originalReplaceState>) {
    const result = originalReplaceState(...args);
    if (!isInternalUrlWrite) notify();
    return result;
  };
  window.addEventListener("popstate", notify);
}

const FILTER_ATTRIBUTES = Object.keys(FILTER_KEYS);
const PATH_ATTRIBUTES = [
  "year",
  "make",
  "model",
  "body_type",
  "vehicle_type",
  "exterior_color",
  "fuel_type",
  "location",
] as const;
type PathFilters = Partial<Record<(typeof PATH_ATTRIBUTES)[number], string[]>>;

function isInventoryListingPath(pathname: string) {
  const segments = pathname.replace(/^\/inventory\/?/, "").split("/").filter(Boolean);
  if (!segments.length) return pathname === "/inventory" || pathname === "/inventory/";

  // Vehicle detail links begin with an inventory ID (for example 3019-...);
  // listing paths may begin with a four-digit vehicle year.
  const firstToken = segments[0].split("-", 1)[0];
  const numericValue = Number(firstToken);
  return !/^\d+$/.test(firstToken) || (numericValue >= 1900 && numericValue <= 2100);
}

const titleCase = (value: string) => value
  .split("-")
  .filter(Boolean)
  .map((part) => {
    const acronyms: Record<string, string> = { bmw: "BMW", gmc: "GMC", ram: "RAM", suv: "SUV" };
    return acronyms[part.toLowerCase()] || `${part.charAt(0).toUpperCase()}${part.slice(1)}`;
  })
  .join(" ");

function readPathOnlyFilters(segments: string[], refinementList: PlainObject) {
  const set = (attribute: keyof PathFilters, value: string) => {
    if (!value || refinementList[attribute]) return;
    // Tolerate comma-separated values here too, so links generated by the old buggy
    // serializer (which crammed multiple selections into one path segment) still parse
    // instead of silently failing.
    const values = value.split(",").filter(Boolean).map(titleCase);
    if (values.length) refinementList[attribute] = values;
  };
  const [vehicleSegment, detailSegment] = segments.map(decodeURIComponent);
  if (!vehicleSegment) return;

  let remainingVehicle = vehicleSegment;
  const yearMatch = remainingVehicle.match(/^(19\d{2}|20\d{2})(?:-|$)/);
  if (yearMatch) {
    set("year", yearMatch[1]);
    remainingVehicle = remainingVehicle.slice(yearMatch[0].length);
  }

  const bodyTypes = ["sport-utility-vehicle", "suv-crossover", "pickup-truck", "hatchback", "convertible", "minivan", "sedan", "coupe", "truck", "van", "suv"];
  const bodyType = bodyTypes.find((value) => remainingVehicle === value || remainingVehicle.endsWith(`-${value}`));
  if (bodyType) {
    set("body_type", bodyType);
    remainingVehicle = remainingVehicle.slice(0, -bodyType.length).replace(/-$/, "");
  }

  const makes = ["mercedes-benz", "aston-martin", "land-rover", "volkswagen", "mitsubishi", "chevrolet", "cadillac", "chrysler", "hyundai", "infiniti", "jaguar", "mazda", "nissan", "subaru", "toyota", "acura", "audi", "bmw", "buick", "dodge", "ford", "gmc", "honda", "jeep", "kia", "lexus", "lincoln", "ram", "volvo"];
  const make = makes.find((value) => remainingVehicle === value || remainingVehicle.startsWith(`${value}-`));
  if (make) {
    set("make", make);
    set("model", remainingVehicle.slice(make.length).replace(/^-/, ""));
  } else if (!yearMatch && !detailSegment) {
    // The established one-segment location form: /inventory/cardora-brampton
    if (vehicleSegment.toLowerCase().startsWith("cardora-")) set("location", vehicleSegment);
    else set("make", vehicleSegment);
  }

  if (!detailSegment) return;
  let remainingDetail = detailSegment;
  const vehicleTypes = ["certified-pre-owned", "used", "new"];
  const vehicleType = vehicleTypes.find((value) => remainingDetail === value || remainingDetail.startsWith(`${value}-`));
  if (vehicleType) {
    set("vehicle_type", vehicleType);
    remainingDetail = remainingDetail.slice(vehicleType.length).replace(/^-/, "");
  }

  // Locations are serialized last. Cardora locations have a stable prefix,
  // which lets us separate them even when a colour has multiple words (such
  // as "Brilliant Red") and is not in a predefined colour list.
  const cardoraLocationStart = remainingDetail.indexOf("cardora-");
  const location = cardoraLocationStart >= 0
    ? remainingDetail.slice(cardoraLocationStart).replace(/^-$/, "")
    : "";
  if (cardoraLocationStart >= 0) {
    remainingDetail = remainingDetail.slice(0, cardoraLocationStart).replace(/-$/, "");
  }

  const fuelTypes = ["gasoline-fuel", "diesel-fuel", "plug-in-hybrid", "flex-fuel", "hybrid", "electric"];
  const fuelType = fuelTypes.find((value) => remainingDetail === value || remainingDetail.endsWith(`-${value}`));
  if (fuelType) {
    set("fuel_type", fuelType);
    remainingDetail = remainingDetail === fuelType
      ? ""
      : remainingDetail.slice(0, -fuelType.length).replace(/-$/, "");
  }
  // The remaining prefix is the colour, regardless of how many words it has.
  set("exterior_color", remainingDetail);
  set("location", location);
}

const slugify = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

function routeValue(value: string) {
  return encodeURIComponent(slugify(value));
}

export function queryValue(value: string) {
  return encodeURIComponent(value.replace(/-/g, "--").replace(/ /g, "-"));
}

function parseQueryValue(value: string) {
  return value.replace(/--/g, "\u0000").replace(/-/g, " ").replace(/\u0000/g, "-");
}

function getRangeBounds(value: unknown): [unknown, unknown] {
  if (Array.isArray(value)) return [value[0], value[1]];
  if (typeof value === "string") {
    const [low = "", high = ""] = value.split(":", 2);
    return [low, high];
  }
  return [undefined, undefined];
}

function getPathFilters(route: PlainObject): PathFilters {
  const filters: PathFilters = {};
  PATH_ATTRIBUTES.forEach((attribute) => {
    const values = route.refinementList?.[attribute] || [];
    if (values.length === 1) filters[attribute] = values;
  });
  if (filters.model && !filters.make) delete filters.model;
  return filters;
}

function serializePublicUrl(route: PlainObject, pathFilters: PathFilters) {
  const params: string[] = [];
  const appended = new Set<string>();
  
  // Get the currently selected makes from the route
  const selectedMakes = new Set<string>(route.refinementList?.make || []);
  
  // Clean up the route state to remove orphaned models BEFORE serialization
  // This ensures models are always removed when their make is removed
  if (route.refinementList?.model && route.refinementList.model.length > 0 && selectedMakes.size > 0) {
    const modelMakeMap = getModelMakeMap();
    const validModels = route.refinementList.model.filter((model: string) => {
      const make = modelMakeMap.get(model);
      // Keep model if its make is in selectedMakes or if make is unknown
      return !make || selectedMakes.has(make);
    });
    
    // Update the route state in-place to remove orphaned models
    if (validModels.length !== route.refinementList.model.length) {
      console.log(`[serializePublicUrl] cleaning up orphaned models from route state. Before: ${route.refinementList.model.join(",")}, After: ${validModels.join(",")}`);
      if (validModels.length === 0) {
        delete route.refinementList.model;
      } else {
        route.refinementList.model = validModels;
      }
    }
  }
  
  const appendFacet = (attribute: string) => {
    const values: string[] = route.refinementList?.[attribute] || [];
    if (!values.length || pathFilters[attribute as keyof PathFilters]?.length) return;

    let serializedValues: string[];
    if (attribute === "model") {
      // Filter models to only include those whose make is in selectedMakes
      serializedValues = values
        .filter((model) => {
          const make = modelMakeAssociations.get(model);
          // Keep the model if:
          // 1. Its make is in selectedMakes, OR
          // 2. Its make is unknown (not yet in map - will be resolved when data loads)
          const isValid = !make || selectedMakes.has(make);
          if (!isValid) {
            console.log(`[serializePublicUrl] filtering out orphaned model: ${model} (make: ${make}, selected: ${Array.from(selectedMakes).join(",")})`);
          }
          return isValid;
        })
        .map((model) => {
          const make = modelMakeAssociations.get(model);
          return make ? `${queryValue(make)};${queryValue(model)}` : queryValue(model);
        });
      // If no valid models remain, don't add the parameter at all
      if (!serializedValues.length) return;
    } else {
      serializedValues = values.map(queryValue);
    }
    
    params.push(`${FILTER_KEYS[attribute]}=${serializedValues.join(",")}`);
    appended.add(attribute);
  };
  const appendRange = (attribute: keyof typeof RANGE_KEYS, index: 0 | 1) => {
    const [low, high] = getRangeBounds(route.range?.[attribute]);
    const value = index === 0 ? low : high;
    if (value !== undefined && value !== "") {
      params.push(`${RANGE_KEYS[attribute][index]}=${encodeURIComponent(String(value))}`);
    }
  };

  // Canonical query order, independent of the order in which filters were selected.
  appendRange("selling_price", 0);
  appendRange("odometer", 0);
  appendFacet("transmission");
  appendRange("selling_price", 1);
  appendRange("odometer", 1);
  FILTER_ATTRIBUTES.forEach((attribute) => {
    if (!appended.has(attribute)) appendFacet(attribute);
  });
  if (route.query) params.push(`q=${encodeURIComponent(route.query)}`);
  const sort = getPublicSort(route.sortBy);
  if (sort) {
    // field/direction are always safe internal identifiers (letters, digits,
    // underscores) and ':' / ',' are valid unencoded in a query string, so
    // this is left un-percent-encoded for a readable URL.
    params.push(`sortBy=status_rank:asc,${sort.field}:${sort.direction.toLowerCase()}`);
  }
  
  const pathValues = (attributes: readonly (keyof PathFilters)[]) =>
    attributes
      .map((attribute) => pathFilters[attribute]?.map(routeValue).join(","))
      .filter((value): value is string => Boolean(value));
  const vehicleSegments = pathValues(["year", "make", "model", "body_type"]);
  const detailSegments = pathValues(["vehicle_type", "exterior_color", "fuel_type", "location"]);
  const path = vehicleSegments.length
    ? `/inventory/${vehicleSegments.join("-")}${detailSegments.length ? `/${detailSegments.join("-")}` : ""}`
    : detailSegments.length
      ? `/inventory/${detailSegments.join("-")}`
      : "/inventory";
  return params.length ? `${path}?${params.join("&")}` : path;
}

function readRouteState(): PlainObject {
  if (typeof window === "undefined") return {};

  const params = new URLSearchParams(window.location.search);
  const refinementList: PlainObject = {};
  const range: PlainObject = {};
  
  let hasExplicitModelEncoding = false;

  for (const [attribute, key] of Object.entries(FILTER_KEYS)) {
    const value = params.get(key);
    if (!value) continue;

    if (attribute === "model") {
      const models: string[] = [];
      const impliedMakes: string[] = [];
      value.split(",").filter(Boolean).forEach((entry) => {
        const [rawMake, rawModel] = entry.includes(";") ? entry.split(";", 2) : [undefined, entry];
        const model = parseQueryValue(rawModel);
        models.push(model);
        if (rawMake) {
          hasExplicitModelEncoding = true;
          const make = parseQueryValue(rawMake);
          impliedMakes.push(make);
          modelMakeAssociations.set(model, make);
        }
      });
      refinementList.model = models;
      if (impliedMakes.length) {
        const existingMakes: string[] = refinementList.make || [];
        refinementList.make = [...new Set([...existingMakes, ...impliedMakes])];
      }
      continue;
    }

    refinementList[attribute] = value.split(",").filter(Boolean).map(parseQueryValue);
  }

  for (const [attribute, [lowKey, highKey]] of Object.entries(RANGE_KEYS)) {
    const low = params.get(lowKey);
    const high = params.get(highKey);
    if (low !== null || high !== null) {
      // React InstantSearch stores a range as "low:high".
      range[attribute] = `${low || ""}:${high || ""}`;
    }
  }

  const route: PlainObject = { refinementList, range };
  
  // Clean up orphaned models ONLY if they came from explicit make;model encoding
  // This prevents removing models when the page first loads with just makes in the URL
  if (hasExplicitModelEncoding && refinementList.model && refinementList.model.length > 0 && refinementList.make && refinementList.make.length > 0) {
    const selectedMakes = new Set<string>(refinementList.make);
    const validModels = refinementList.model.filter((model: string) => {
      const make = modelMakeAssociations.get(model);
      // Keep model if its make is in selectedMakes or if we don't know its make yet
      return !make || selectedMakes.has(make);
    });
    
    // Only update if we actually filtered something out
    if (validModels.length === 0) {
      delete refinementList.model;
    } else if (validModels.length < refinementList.model.length) {
      refinementList.model = validModels;
    }
  }
  
  const query = params.get("q");
  if (query) route.query = query;

  // Current format: a single sortBy param carrying the full criteria list,
  // including status_rank, e.g. "status_rank:asc,price:asc".
  const sortByParam = params.get("sortBy");
  // Legacy formats, still accepted so previously shared links keep working.
  const legacySortField = params.get("sortField");
  const legacySortDirection = params.get("sortDirection")?.toUpperCase();
  const legacySort = params.get("sort");

  if (sortByParam) {
    const criteria = sortByParam.split(",").filter(Boolean);
    const primaryCriterion = criteria.find((c) => !c.startsWith("status_rank:")) || criteria[0];
    const [field, direction] = primaryCriterion?.split(":", 2) ?? [];
    if (field && direction && (direction.toUpperCase() === "ASC" || direction.toUpperCase() === "DESC")) {
      route.sortField = field;
      route.sortDirection = direction.toUpperCase();
    }
  } else if (legacySortField && (legacySortDirection === "ASC" || legacySortDirection === "DESC")) {
    route.sortField = legacySortField;
    route.sortDirection = legacySortDirection;
  } else if (legacySort) {
    route.sortBy = legacySort;
  }
 
  const pathFilters = window.history.state?.__inventoryPathFilters as PathFilters | undefined;
  if (pathFilters && window.location.pathname.startsWith("/inventory/")) {
    PATH_ATTRIBUTES.forEach((attribute) => {
      if (pathFilters[attribute]?.length) refinementList[attribute] = pathFilters[attribute];
    });
  }

  // A fresh request has no history state. Decode the canonical path values
  // for any refinements not already supplied in the (non-path) query string.
  const segments = window.location.pathname.replace(/^\/inventory\/?/, "").split("/").filter(Boolean);
  if (!pathFilters && isInventoryListingPath(window.location.pathname)) {
    readPathOnlyFilters(segments, refinementList);
  }

  return route;
}

export const createInventoryStateMapping = (config: AppConfig) => {
  const indexName = config.site.collection || "";
  const defaultSort = `${indexName}/sort/status_rank:asc,created_at:desc`;

  return {
    stateToRoute(uiState: UiState) {
      const state = uiState[indexName] || {};
      return {
        query: state.query || undefined,
        refinementList: state.refinementList || {},
        range: state.range || {},
        sortBy: state.sortBy && state.sortBy !== defaultSort ? state.sortBy : undefined,
      };
    },

    routeToState(routeState: PlainObject | undefined | null) {
      const route = routeState || {};
      const sortBy = route.sortField && (route.sortDirection === "ASC" || route.sortDirection === "DESC")
        ? `${indexName}/sort/status_rank:asc,${getInternalSortField(route.sortField)}:${route.sortDirection.toLowerCase()}`
        : route.sortBy || defaultSort;
      return {
        [indexName]: {
          query: route.query || "",
          refinementList: route.refinementList || {},
          range: route.range || {},
          sortBy,
        },
      };
    },
  };
};

export function createInventoryRouter(_config: AppConfig) {
  watchExternalUrlChanges();
  let callback: ((route: PlainObject) => void) | null = null;
  const initialRoute = readRouteState();
  let previousRoute = initialRoute;
  let pathFilters: PathFilters =
    typeof window !== "undefined"
      ? window.history.state?.__inventoryPathFilters || getPathFilters(initialRoute)
      : {};

  // Tracks the last URL we actually wrote via history.replaceState, so we can
  // skip no-op writes below. See performWrite for why this matters.
  let lastWrittenUrl: string | null = null;

  if (typeof window !== "undefined" && Object.keys(pathFilters).length && window.location.pathname === "/inventory") {
    const bootstrapUrl = serializePublicUrl(initialRoute, pathFilters);
    isInternalUrlWrite = true;
    window.history.replaceState({ ...initialRoute, __inventoryPathFilters: pathFilters }, "", bootstrapUrl);
    isInternalUrlWrite = false;
    lastWrittenUrl = bootstrapUrl;
  }

  const performWrite = (route: PlainObject, filters: PathFilters) => {
    if (typeof window === "undefined") return;
    if (!isInventoryListingPath(window.location.pathname)) return;

    const url = serializePublicUrl(route, filters);

    if (url === lastWrittenUrl) return;
    lastWrittenUrl = url;

    const state = { ...route, __inventoryPathFilters: filters };

    // Safari often jumps scroll UP on history.replaceState. Only correct
    // upward jumps so bottom infinite-scroll growth is not fought.
    const scrollY = window.scrollY;
    isInternalUrlWrite = true;
    window.history.replaceState(state, "", url);
    isInternalUrlWrite = false;
    if (window.scrollY < scrollY - 1) {
      window.scrollTo(0, scrollY);
    }
  };

  const resync = () => performWrite(previousRoute, pathFilters);
  activeRouterResync = resync;

  const notify = () => {
    if (!isInventoryListingPath(window.location.pathname)) return;
    const route = readRouteState();
    previousRoute = route;
    if (window.location.pathname === "/inventory") {
      pathFilters = getPathFilters(route);
    }
    callback?.(route);
  };
  externalUrlListeners.add(notify);

  return {
    read: readRouteState,

    write(nextRoute: PlainObject) {
      pathFilters = getPathFilters(nextRoute);
      previousRoute = nextRoute;
      performWrite(nextRoute, pathFilters);
    },

    resync,

    createURL(routeState: PlainObject) {
      // InstantSearch only uses this for links; write() is the canonical serializer.
      const query = routeState.query ? `?q=${encodeURIComponent(routeState.query)}` : "";
      return `${window.location.origin}/inventory${query}`;
    },

    onUpdate(nextCallback: (route: PlainObject) => void) {
      callback = nextCallback;
    },

    dispose() {
      externalUrlListeners.delete(notify);
      if (activeRouterResync === resync) activeRouterResync = null;
      callback = null;
    },
  };
}